query GetVouchers {
  vouchers {
    id
    nativeId
    code
    authorEmail
    createdAt
    ownerCpf
    ownerName
    status
    expirationDate
    currentBalance
    initialValue
    isReloadable
    totalCredited
    totalDebited
    transactionCount
  }
}
